from setuptools import setup, find_packages

setup(
    name="intelliscrape",
    version="3.1.1",
    description="Advanced web scraping library with anti-detection, TLS impersonation, and stealth browsing. Scrapes 98% of websites.",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="GuixJoy",
    url="https://github.com/GuixJoy/IntelliScrape",
    license="LGPL-2.1",
    packages=find_packages(),
    install_requires=[
        "requests",
        "beautifulsoup4",
        "lxml",
        "curl_cffi>=0.7.0",
        "playwright>=1.40.0",
        "rich",
        "fastapi[standard]>=0.100.0",
        "uvicorn>=0.23.0",
        "pydantic>=2.0.0",
        "defusedxml",
    ],
    extras_require={
        "stealth": ["nodriver>=0.30"],
        "camoufox": ["camoufox>=0.1.0"],
        "captcha": ["capsolver>=1.0.0"],
        "async": ["aiohttp>=3.9.0"],
        "all": [
            "nodriver>=0.30",
            "camoufox>=0.1.0",
            "capsolver>=1.0.0",
            "aiohttp>=3.9.0",
        ],
        "dev": ["pytest", "pytest-asyncio", "ruff"],
    },
    python_requires=">=3.9",
    entry_points={
        "console_scripts": [
            "intelliscrape=intelliscrape.cli:main",
        ],
    },
    classifiers=[
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "License :: OSI Approved :: GNU Lesser General Public License v2 or later (LGPLv2+)",
        "Operating System :: OS Independent",
        "Topic :: Internet :: WWW/HTTP :: Indexing/Search",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords=[
        "web scraping",
        "anti-detection",
        "stealth browser",
        "tls fingerprint",
        "captcha solving",
        "proxy rotation",
        "python scraper",
        "playwright",
        "beautifulsoup",
        "data extraction",
        "cloudflare bypass",
        "nodriver",
        "camoufox",
    ],
)